In [1]:
import numpy as np

In [5]:
matriks = np.random.randint(1, 100, size=(5, 5))

In [6]:
nilai_max = matriks.max()
nilai_min = matriks.min()
nilai_rata = matriks.mean()

In [7]:
print("Matriks 5x5:")
print(matriks)
print("\nNilai Maksimum :", nilai_max)
print("Nilai Minimum  :", nilai_min)
print("Nilai Rata-rata:", nilai_rata)

Matriks 5x5:
[[35 48 28 13  9]
 [ 1  4 99 16 65]
 [48 12 88 32  4]
 [72 55 89 48 90]
 [ 1 62 39 27 70]]

Nilai Maksimum : 99
Nilai Minimum  : 1
Nilai Rata-rata: 42.2
